### ISSUE TITLE
Is this working with the latest version of Laravel?

### ISSUE THREAD

**Issue by yeltsinxyz** [neoighodaro-articles/e-commerce-laravel-vue#3]
Hello,

I've made everything as described in the codes but I did translate the ```Orders``` to ```Pedidos``` and ```Products``` to ```Produtos```.

When I run ```php artisan serve``` it just shows a blank page. No error, not even in PHP.

So what I did wrong? :(

This is my repo:
https://github.com/yeltsinxyz/ecommerce

**Comment by yeltsinxyz** [comment]
Actually, I did some sh*t in my repo. My main problem is not PHP error is a JS error w/ a library you are using called axios. 

Searched on the web/stackoverflow. No solutions :(

See: https://github.com/yeltsinxyz/ecommerce/issues/1

**Comment by yeltsinxyz** [comment]
Not using anymore. 😢

**Comment by afemarksola** [comment]
@yeltsinxyz Hi, please do you later know the solution to this issue. I also got the same blank page (no error message) after using the code. when I route web.php to other welcome page it loaded but the landing page won't load.

**Comment by neoighodaro** [comment]
This is a really old code but what is on your logs?
